"""工具函数，用于生成vk-hid和ecode-hid的映射文件"""

from pathlib import Path

try:
    from inputflow.keymaps.base import (
        ECODE_TO_HID_BTN,
        ECODE_TO_HID_KEY,
        VK_TO_HID_BTN,
        VK_TO_HID_KEY,
    )
except ImportError:
    from .base import (
        ECODE_TO_HID_BTN,
        ECODE_TO_HID_KEY,
        VK_TO_HID_BTN,
        VK_TO_HID_KEY,
    )


def generate_vk_map_file(file_path: str | Path):
    """Generate bidirectional mapping files for VK to HID and HID to VK"""

    # 将映射写入文件
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write('"""\n')
        f.write('This file is automatically generated by keymaps.utils.\n')
        f.write('Do not modify this file.\n')
        f.write('VK-HID bidirectional mapping dictionary.\n')
        f.write('"""\n\n')

        f.write('VK_TO_HID: dict[int | str, int] = {\n')
        for btn, hid in sorted(VK_TO_HID_BTN.items(), key=lambda x: str(x[0])):
            f.write(f"    '{btn}': 0x{(hid << 8) + 0xAA:04X},\n")
        for vk, hid in sorted(VK_TO_HID_KEY.items()):
            f.write(f'    {vk}: 0x{hid:02X},\n')
        f.write('}\n\n')

        f.write('HID_TO_VK: dict[int, int | str] = {v: k for k, v in VK_TO_HID.items()}\n')

        f.write('\n\n')
        f.write('def vk_to_hid(vk: int | str) -> int:\n')
        f.write("    return VK_TO_HID.get(vk, 'UNKNOWN')\n")

        f.write('\n\n')
        f.write('def hid_to_vk(hid: int) -> int | str:\n')
        f.write('    return HID_TO_VK.get(hid, 0x00)\n')


def generate_ecode_map_file(file_path: str | Path):
    """Generate ECode to HID and HID to ECode bidirectional mapping files"""
    import evdev.ecodes as e

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write('"""\n')
        f.write('This file is automatically generated by keymaps.utils.\n')
        f.write('Do not modify this file.\n')
        f.write('ECode-HID bidirectional mapping dictionary.\n')
        f.write('"""\n\n')

        f.write('ECODE_TO_HID: dict[int, int] = {\n')
        for ecode, hid in sorted(ECODE_TO_HID_BTN.items()):
            btn_name = e.bytype.get(e.EV_KEY, {}).get(ecode, 'UNKNOWN')
            f.write(f'    {ecode}: 0x{(hid << 8) + 0xAA:04X},  # {btn_name}\n')
        for ecode, hid in sorted(ECODE_TO_HID_KEY.items()):
            key_name = e.bytype.get(e.EV_KEY, {}).get(ecode, 'UNKNOWN')
            f.write(f'    {ecode}: 0x{hid:02X},  # {key_name}\n')
        f.write('}\n\n')

        f.write('HID_TO_ECODE: dict[int, int] = {v: k for k, v in ECODE_TO_HID.items()}\n')

        f.write('\n\n')
        f.write('def ecode_to_hid(code: int) -> int:\n')
        f.write('    return ECODE_TO_HID.get(code, 0x00)\n')

        f.write('\n\n')
        f.write('def hid_to_ecode(hid_id: int) -> int:\n')
        f.write('    return HID_TO_ECODE.get(hid_id, 0x00)\n')


def generate_hid_map_file(file_path: str | Path):
    """Generate HID to KeyName and KeyName to HID bidirectional mapping files"""
    import evdev.ecodes as e

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write('"""\n')
        f.write('This file is automatically generated by keymaps.utils.\n')
        f.write('Do not modify this file.\n')
        f.write('HID-KeyName bidirectional mapping dictionary.\n')
        f.write('"""\n\n')

        f.write('NAME_TO_HID: dict[str, int] = {\n')
        for ecode, hid in sorted(ECODE_TO_HID_BTN.items()):
            btn_name = e.bytype.get(e.EV_KEY, {}).get(ecode, 'UNKNOWN')
            f.write(f"    '{str(btn_name).replace("'", '')}': 0x{(hid << 8) + 0xAA:04X},\n")
        for ecode, hid in sorted(ECODE_TO_HID_KEY.items()):
            key_name = e.bytype.get(e.EV_KEY, {}).get(ecode, 'UNKNOWN')
            f.write(f"    '{str(key_name).replace("'", '')}': 0x{hid:02X},\n")
        f.write('}\n\n')

        f.write('HID_TO_NAME: dict[int, str] = {v: k for k, v in NAME_TO_HID.items()}\n')

        f.write('\n\n')
        f.write('def name_to_hid(name: str) -> int:\n')
        f.write('    return NAME_TO_HID.get(name, 0x00)\n')

        f.write('\n\n')
        f.write('def hid_to_name(hid_id: int) -> str:\n')
        f.write("    return HID_TO_NAME.get(hid_id, 'UNKNOWN')\n")


def generate_maps():
    """生成vk_map.py和ecode_map.py文件"""

    try:
        import evdev
    except ImportError:
        print('evdev unavailable.')
        evdev = None

    current_dir = Path(__file__).parent

    if evdev:
        ecode_map_path = current_dir / 'ecode_map.py'
        generate_ecode_map_file(ecode_map_path)
        print(f'Generated {ecode_map_path}')

        hid_map_path = current_dir / 'hid_map.py'
        generate_hid_map_file(hid_map_path)
        print(f'Generated {hid_map_path}')

    else:
        vk_map_path = current_dir / 'vk_map.py'
        generate_vk_map_file(vk_map_path)
        print(f'Generated {vk_map_path}')


if __name__ == '__main__':
    generate_maps()
